name: Github Pages Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Install packages
        run: yarn install --no-lockfile
      - name: Inject variables into configuration files
        run: yarn inject-config
        env:
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
      - name: Build app
        run: yarn build
        if: ${{ github.event.repository.name != 'boilerplate' }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event.repository.name != 'boilerplate' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
          enable_jekyll: false
